[client]
toolbarMode = "minimal"

[ui]
hideTopBar = true

[theme]
#base = "light"
primaryColor = "#A7A2A9"
backgroundColor = "#08090A"
secondaryBackgroundColor = "#33415c"
textColor = "#fafafa"
font = "sans serif"